# Copyright (c) 2018 Mainflux
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:

  ###
  # NGINX
  ###
  nginx:
    image: nginx:alpine
    container_name: edgex-nginx
    volumes:
      - $PWD/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/proxy/nginx/ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - $PWD/proxy/nginx/ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - $PWD/proxy/nginx/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
  
  ###
  # MongoDB
  ###
  mongo:
    image: mongo:latest
    container_name: edgex-mongodb
    command: --smallfiles --nojournal
    ports:
      - "27017:27017"

  ###
  # EdgeX Auth
  ###
  edgex-auth:
    image: drasko/edgex-auth:latest
    container_name: edgex-auth
    links:
      - mongo
    ports:
      - "8089:8089"
